apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: lm4ulh4xf-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/jsmid/rhtap-qe:a3b984a5f28cf2202d840c87f8fc2070a6f0c7c7@sha256:e1c11f064bcd9faac8d8a178a8f14898bdcf40091186acbf895ca99cb601a7b8
        name: container-image  
